fix: make execute_package() posix compliant

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -38,13 +38,23 @@ EOF
 }
 
 execute_package() {
+  TMP="$(mktemp)"
   ACTION=$1
   PKGDIR=$2
   PKGFILE="$PKGDIR/pkgrc"
   PKGNAME="${PKGDIR##*/}"
 
-  debug "executing package action '$ACTION' on '$PKGDIR' ..."
-  sh -s < <(cat <<EOF
+  cat > "$TMP" <<EOF
+#!/usr/bin/env sh
+set -o errexit  # exit on command failure
+set -o nounset  # exit on undeclared variable usage
+
+# remove this temporal file
+rm '$TMP'
+
+# dotfiles configuration
+export DOTFILES_LIB=$DOTFILES_LIB
+
 # logging configuration
 export DOTFILES_LOGLEVEL=$DOTFILES_LOGLEVEL
 export DOTFILES_TRACE=$DOTFILES_TRACE
@@ -66,8 +76,6 @@ cd "$PKGDIR" 2>/dev/null || die "package not found: $PKGNAME"
 if type "$ACTION" >/dev/null 2>&1; then
   debug "running '$ACTION' action ..."
 
-  set -o errexit  # exit on command failure
-  set -o nounset  # exit on undeclared variable usage
   if [ $DOTFILES_TRACE -gt 0 ]; then
     set -o xtrace # enable shell command tracing
   fi
@@ -77,7 +85,9 @@ else
   warn "$ACTION action not supported"
 fi
 EOF
-)
+
+  debug "executing package action '$ACTION' on '$PKGDIR' ..."
+  sh -s < "$TMP"
 }
 
 while [ $# -gt 0 ]; do
